# composeファイルのバージョン指定
#　Doc: https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9"

services:
  mysql:
    build: ./server/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306
    container_name: ${PROJECT_NAME}-mysql
    volumes:
      - db-store:/var/lib/mysql

  php:
    build:
      context: ./server/php
      args:
        WORKDIR: $WORKDIR
        MYSQL_DATABASE: $MYSQL_DATABASE
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ./api:$WORKDIR

  nginx:
    image: nginx:1.20-alpine
    ports:
      - $API_PORT:80
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./api:$WORKDIR
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: $WORKDIR
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: $PMA_HOST
      PMA_USER: $MYSQL_USER
      PMA_PASSWORD: $MYSQL_PASSWORD
    links:
      - mysql
    ports:
      - 4040:80
    container_name: ${PROJECT_NAME}-pma
    volumes:
      - ./phpmyadmin/sessions:/sessions
    
  # Nuxt Setup1
  # TODO: npm init nuxt-appコマンド実行前
  #
  # nuxt:
  #   build:
  #     context: ./www
  #     args:
  #       WORKDIR: ${WORKDIR}/
  #   command: npm run dev
  #   volumes:
  #     - ./www:/${WORKDIR}
  #   container_name: ${PROJECT_NAME}-nuxt
  #   ports:
  #     - "$FRONT_PORT:3000"
  
  # Nuxt Setup2
  # TODO: npm init nuxt-appコマンド実行後
  #
  # nuxt:
  #   build:
  #     context: ./www
  #     args:
  #       WORKDIR: ${WORKDIR}/www.${PROJECT_NAME}
  #   command: npm run dev
  #   volumes:
  #     - ./www/www.${PROJECT_NAME}:/${WORKDIR}/www.${PROJECT_NAME}
  #   container_name: ${PROJECT_NAME}-nuxt
  #   ports:
  #     - "$FRONT_PORT:3000"


volumes:
  db-store:

